## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import json

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
0,0,Mount Pleasant,US,74.05,scattered clouds,32.7941,-79.8626,Best Western Patriots Point
1,7,Arraial Do Cabo,BR,75.16,few clouds,-22.9661,-42.0278,Pousada Porto Praia
2,9,Ribeira Grande,PT,72.00,few clouds,38.5167,-28.7000,Quinta da Meia Eira
3,11,San Patricio,US,75.06,scattered clouds,28.0170,-97.5169,"Motel 6 Sinton, TX"
4,13,Noumea,NC,75.99,few clouds,-22.2763,166.4572,Hôtel Le Lagon

In [3]:
# 2. Using the template add the city name, the country code, 
# the weather description and maximum temperature for the city.

info_box_template = """
<dl>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Description</dt><dd>{Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# <dt>Hotel Name</dt><dd>{Hotel Name}</dd>



# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
usa_df=vacation_df.loc[vacation_df['Country']=='US']
usa_df.head(25)

,City_ID,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
0,0,Mount Pleasant,US,74.05,scattered clouds,32.7941,-79.8626,Best Western Patriots Point
3,11,San Patricio,US,75.06,scattered clouds,28.0170,-97.5169,"Motel 6 Sinton, TX"
17,58,Hilo,US,72.63,broken clouds,19.7297,-155.0900,Hilo Hawaiian Hotel
40,125,Kapaa,US,75.52,light rain,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
67,199,Havelock,US,76.95,overcast clouds,34.8791,-76.9013,Sherwood Motel
88,243,Kahului,US,76.84,clear sky,20.8947,-156.4700,Maui Seaside Hotel
120,322,Rincon,US,72.86,broken clouds,32.2960,-81.2354,Days Inn Rincon
171,464,Elizabeth City,US,71.01,broken clouds,36.2946,-76.2511,Hampton Inn Elizabeth City
234,671,Morgan City,US,73.00,clear sky,29.6994,-91.2068,Hampton Inn & Suites Morgan City
241,690,Myrtle Beach,US,77.09,scattered clouds,33.6891,-78.8867,Bay View Resort Myrtle Beach

In [6]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = usa_df.loc[usa_df['City']=='Myrtle Beach']
vacation_end   = usa_df.loc[usa_df['City']=='Myrtle Beach']
vacation_stop1 = usa_df.loc[usa_df['City']=='Morgan City']
vacation_stop2 = usa_df.loc[usa_df['City']=='Rincon'] 
vacation_stop3 = usa_df.loc[usa_df['City']=='Mount Pleasant']

vacation_start
# print(vacation_stop1)
# print(vacation_stop2)
# print(vacation_stop3)

,City_ID,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
241,690,Myrtle Beach,US,77.09,scattered clouds,33.6891,-78.8867,Bay View Resort Myrtle Beach

In [7]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.

startn = vacation_start.to_numpy()
endn = vacation_end.to_numpy()
stop1n = vacation_stop1.to_numpy()
stop2n = vacation_stop2.to_numpy()
stop3n = vacation_stop3.to_numpy()

In [8]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.

startnumpy=startn[0][5],startn[0][6]
endnumpy = endn[0][5],endn[0][6]
stop1numpy = stop1n[0][5],stop1n[0][6]
stop2numpy = stop2n[0][5],stop2n[0][6]
stop3numpy=stop3n[0][5],stop3n[0][6]

In [9]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
start_to_end = gmaps.directions_layer(startnumpy, endnumpy, 
                                      waypoints=[stop1numpy,stop2numpy,stop3numpy],travel_mode='DRIVING')
fig.add_layer(start_to_end)
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
0,690,Myrtle Beach,US,77.09,scattered clouds,33.6891,-78.8867,Bay View Resort Myrtle Beach
1,671,Morgan City,US,73.00,clear sky,29.6994,-91.2068,Hampton Inn & Suites Morgan City
2,322,Rincon,US,72.86,broken clouds,32.2960,-81.2354,Days Inn Rincon
3,0,Mount Pleasant,US,74.05,scattered clouds,32.7941,-79.8626,Best Western Patriots Point

In [13]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Description</dt><dd>{Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
city_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [14]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(31.5,-82.5), zoom_level=5)
marker_layer = gmaps.marker_layer(locations, info_box_content=city_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))